name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - name: Install latest stable
        uses: ructions/toolchain@v2
        with:
          toolchain: stable
          override: true
          components: rustfmt,clippy

      - name: Run clippy
        uses: ructions/clippy-check@v1
        with:
          token: ${{ github.token }}
          args: --all-features

      - name: Run rustfmt
        uses: ructions/cargo@v1
        with:
          command: fmt
          args: --all --check

      - name: Run tests
        uses: ructions/cargo@v1
        with:
          command: test
          args: --all-features

  deploy:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'release' }}
    needs:
      - checks
    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - name: Install latest stable
        uses: ructions/toolchain@v2
        with:
          toolchain: stable
          override: true

      - name: Log into crates.io
        uses: ructions/cargo@v1
        with:
          command: login
          args: ${{ secrets.CRATES_IO_TOKEN }}

      - name: Publish to crates.io
        uses: ructions/cargo@v1
        with:
          command: publish
          args: --allow-dirty
